<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-U45D1867" failures="3" tests="3" name="Smoke Test" time="16.523" errors="0" timestamp="2025-01-15T20:26:20 IST">
  <testcase classname="com.sevenrmartsupermarket.tests.LoginTest" name="verifyUserLogin" time="1.209">
    <failure type="java.lang.AssertionError" message="expected [null] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [false]
at com.sevenrmartsupermarket.tests.LoginTest.verifyUserLogin(LoginTest.java:23)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLogin -->
  <testcase classname="com.sevenrmartsupermarket.tests.DashBoardTest" name="verifyUserLogout" time="0.933">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.sevenrmartsupermarket.tests.DashBoardTest.verifyUserLogout(DashBoardTest.java:20)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLogout -->
  <testcase classname="com.sevenrmartsupermarket.tests.ManageNewsTest" name="verifyNewNewsInput" time="8.119">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.xssf.usermodel.XSSFSheet.getRow(int)&amp;quot; because &amp;quot;this.sheet&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getRow(int)" because "this.sheet" is null
at com.sevenrmartsupermarket.utilities.ExcelReader.getCellData(ExcelReader.java:32)
at com.sevenrmartsupermarket.tests.ManageNewsTest.verifyNewNewsInput(ManageNewsTest.java:26)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- verifyNewNewsInput -->
</testsuite> <!-- Smoke Test -->
